- DataUtil/interface/TreeWriter.h
Return value of TreeWriter::GetBaseURL() changed to fBaseURL.Data()
> Bugfix: GetBaseURL was returning invalid string

- DataUtil/interface/TreeWriter.h
- PhysicsMod/dict/TemplateModsLinkDef.h
- TreeMod/interface/HLTFwkMod.h
- TreeMod/src/HLTFwkMod.cc
Bugfix: Dictionary for SkimMod<PFTau> was not generated due to a missing #include.
Performance: HLTFwkMod (used in most of the analyses) was allocating memory for each trigger object for each event. Made more efficient by using TClonesArray and non-allocation new.
> Bugfix and minor performance improvements

- DataTree/dict/PileupEnergyDensityColLinkDef.h
There was a bug in the LinkDef file for PileupEnergyDensity which was causing end-of-job crashes. The reason of the crash is deep in the ROOT I/O machinery but supposedly due to virtual object members (for fRhoKt6CaloJets and so on) being created but not properly used. This in turn was causing the cleanup in the TTree destructor to double-free.
> bugfix LinkDef of PileupEnergyDensity

- bin/setup.sh
- bin/setupExternal.sh
MitAna/bin/setup.sh will now call setupExternal.sh, which sets up scram configuration XMLs according to the available environment. The same script is called from run.sh when T2_MIT CVMFS is not available, and will work properly. The latter use case is not even supported though.
Corresponding scripts will be removed from MitPhysics. It would not be a problem if someone uses this version of MitAna but does not update MitPhysics; it merely results in same setup procedure repeated.
> Move external installation

- DataCont/interface/RefArray.h
- TreeMod/interface/Analysis.h
- TreeMod/interface/HLTFwkMod.h
- TreeMod/interface/HLTMod.h
- TreeMod/src/Analysis.cc
- TreeMod/src/BaseMod.cc
- TreeMod/src/HLTFwkMod.cc
- TreeMod/src/HLTMod.cc
In order to have a macro that can run on normal files and private MC files that lack HLT information, switches are added to the HLTMod and HLTFwkMod to allow skipping processing if no HLT data is there. This turned out to be a bigger surgery than initially anticipated since HLTFwkMod is hidden in Analysis.
> adding option to dynamically skip HLT when data is not present

- TreeMod/interface/HLTMod.h
- TreeMod/src/BaseMod.cc
- TreeMod/src/HLTMod.cc
Aborting when there is no data and aborting when trigger did not fire are not mutually exclusive. Need two independent booleans.
> skip mode was not the right implementation

- TreeMod/interface/OutputMod.h
- TreeMod/src/OutputMod.cc
OutputMod was indeed creating branches at the first event to be processed, and for a good reason. The pointers to the objects filled in the branches are available only after LoadBranch, which is only possible in Process() function. If a null pointer is passed to the tree, ROOT will automatically allocate a new object, and the current implementation of TreeWriter in fact forbids a null pointer to be passed for this reason.
We can work around this problem and still be able to write skims by requiring the OutputMod to be always a supermod (therefore OutputMod::Process is guaranteed to be reached) but adding "conditions" = list of modules at least one of which must be active (i.e. not in an aborted path). This is very similar to the CMSSW OutputModule implementation, where output module is …
> solved 'empty-tree' problem by requiring OutputMod to be a supermodule

- .gitignore
- PhysicsMod/dict/MitAnaPhysicsModLinkDef.h
- PhysicsMod/interface/MaskCollectionMod.h
- PhysicsMod/src/MaskCollectionMod.cc
Id modules can now publish an array of bools. This simple module can be used when both the filtered collection of objects and the bool array are wanted. The module takes an input particle collection and the bool array produced from it, and filters out the "failing" objects.
> new module MaskCollectionMod

- DataTree/interface/Muon.h
- DataTree/interface/MuonQuality.h
As pointed out by Dylan. We were lacking variables that cannot be / are difficult to calculate on the fly but are used for standard muon Id.
> Adding ValidFraction, NMatchedStations, Chi2LocalPosition, Chi2LocalMomentum

- TreeMod/interface/Analysis.h
- TreeMod/interface/BaseMod.h
- TreeMod/interface/Selector.h
- TreeMod/src/AnaFwkMod.cc
- TreeMod/src/Analysis.cc
- TreeMod/src/HLTFwkMod.cc
- TreeMod/src/HLTMod.cc
- TreeMod/src/OutputMod.cc
- TreeMod/src/Selector.cc
. Further fixes on HLT-related modules to allow running on files with no HLT data.
. Fixed bug in OutputMod where AllEvent header was filled before updating the run tree entry index of the current header
. More consistent handling of OutputMod at the Analysis level (new function AddOutputMod which inserts an output module to the end of the SuperModules list)
> Hltfwkmod bugfix + OutputMod updates

- DataTree/interface/FatJet.h
- DataTree/interface/XlFatJet.h
Key change was moving of subjet computation/storing. Also moved some substructure floats that can be computed on top of Bambu to speed up production. Finally, all doubles are now floats.
> Moved substructure info from FatJet to XlFatJet

- TreeMod/src/OutputMod.cc
The last bugfix on OutputMod actually didn't fix the problem where the skim output will have inconsistent information in the AllEvent tree.
To give a bit more detail: AllEvent tree is used to record the information of the events that were processed, including those which were skipped. Its only branch is a collection of EventHeader, and the header is filled with information in FillAllEventHeader function.
One piece of information that EventHeader holds is the entry number in the RunInfo tree for the corresponding run data. When we run the skim over multiple files, the RunInfo tree in the output file will no longer have the same ordering / entries. Therefore this specific variable fRunEntry must be updated in the EventHeaders. Before this bug fix, AllEventHeader was copied directly from the …
> fix runentry of allevent + MC event weight for skimmed events

- PhysicsMod/interface/FastJetMod.h
- PhysicsMod/src/FastJetMod.cc
I changed the way objects are loaded to match Yutaro's new method. I also removed some warnings and return of a NULL pointer that happens when the number of jets is zero. (This happens with a high pT cut.) I think it would be better to get an array with size 0 than an error during later mods. I changed the default algo to AKt, since it seems like everyone else uses that. I can change back though and change my workflow.
> FastJetMod

- DataTree/dict/FatJetColLinkDef.h
- DataTree/interface/FatJet.h
One of the failure mode in the current 042 tag is in the XML parsing, but we have been seeing "data corrupted" type of errors in FatJet. It is highly unlikely that the XML problem will cause only the FatJet class to be corrupted, so as a safety measure I'm adding ClassDef and linkdef lines for the nested structs in FatJet. In fact, as far as I know, we have never had classes with nested class / struct (and std::vector thereof) being written to Bambu files, and it's not clear to me whether it is enough to have a dictionary for FatJet. In fact, we had no Streamer for the Track/SV/LeptonData structs (now we do).
> Adding ClassDef and linkdefs for Track/SV/LeptonData

- Catalog/src/Catalog.cc
- DataUtil/interface/Cacher.h
- DataUtil/src/Cacher.cc
- TreeMod/interface/AnaFwkMod.h
- TreeMod/interface/Analysis.h
- TreeMod/interface/Selector.h
- TreeMod/src/AnaFwkMod.cc
- TreeMod/src/Analysis.cc
- TreeMod/src/Selector.cc
- bin/requestFile.sh
This is the branch I have been running my jobs with recently. Full-local caching (download from local hadoop onto the worker node disk) is implemented through new options in the Cacher and Catalog.
It involved some surgeries for the following reason:
*  The current cacher implementation has a hard-coded number of files to cache ahead, which is 2.
*  Each condor job downloading 2 files on top of the one that is being processed is a bit too much. The jobs can reach the allocated space limit and get held. So in full-local mode, we should only cache 1 file ahead.
*  Making Cacher configurable was simple. However, only one file ahead means that the following can happen:
1. File i gets done, with file i+1 in the cache.
2. Job checks that file i+1 exists.
3. Job starts working on file i+1 while …
> Full local caching

- TreeMod/python/bambu.py
- TreeMod/src/Selector.cc
- bin/analysis.py
- bin/requestFile.sh
- bin/runOnDatasets.py
- bin/start.sh
- config/condor_template.jdl
*  requestFile.sh
- Using cp from FUSE instead of hdfs get when full-local copy is invoked
- Improved comments
- Try xrdcp 20 times in case the server is irreponsive
- Bugfix related to unsetting and setting back environment variables
*  Selector.cc
- Aborting analysis when cache times out
*  start.sh (python submission executable)
- Writing a .rootrc to make sure the stack trace is given in case of failure
- Removing all output files when the job failed to ensure condor goes to held state
*  Python tools
- A new dictionary analysis.custom for user-defined variables
- Improved readability with added comments and more streamlined information flow
> Fixes and additions

- bin/runOnDatasets.py
Yet another bug fix, taking the advantage of the fact that we have not tagged yet..
Output directories were not created automatically when transfer_output_remaps was used. (It was before but the line got deleted during recent updates)
> Fixing a bug reported by Brad

- PhysicsMod/src/RunLumiSelectionMod.cc
- PhysicsMod/src/RunSelectionMod.cc
- TAM/BuildFile.xml
- TAM/interface/TAMSelector.h
- TAM/src/TAMSelector.cxx
- TreeMod/interface/Analysis.h
- TreeMod/interface/Selector.h
- TreeMod/src/Analysis.cc
- TreeMod/src/CatalogingMod.cc
- TreeMod/src/HLTFwkMod.cc
- TreeMod/src/HLTMod.cc
- TreeMod/src/MCFwkMod.cc
- TreeMod/src/OutputMod.cc
- TreeMod/src/Selector.cc
- bin/analysis.py
- bin/runOnDatasets.py
We had a functionality of using TTreeCache, but the implementation was somewhat peculiar (and also would cause segfaults because it would access a null pointer).
Since there is no need to own the cache object (TFile internally holds it), I removed the fTreeCache member from TAMSelector. Also the cache size member variable was removed, since whatever you set it to, the maximum cache size is limited to the size of the chunks used when writing the bambu files (default 30MB - might want to increase it in future versions).
Another change is in the "look-ahead" tree, which is used only to detect the run transition. (In my opinion this mechanism, in which we write an entire tree for just recording the run number of each event, is a bit wasteful, so perhaps we can change the way we do this …
> Reviving input caching (ROOT level)

- PhysicsMod/dict/MitAnaPhysicsModLinkDef.h
- PhysicsMod/interface/RunLumiListMod.h
- PhysicsMod/src/RunLumiListMod.cc
- TreeMod/dict/MitAnaTreeModLinkDef.h
- TreeMod/interface/BooleanMod.h
- TreeMod/src/BooleanMod.cc
- bin/makeJson.py
- macros/listLumi.py
RunLumiListMod is not for real analysis but is to create a TTree that contains the run & lum info of the files that are processed. The result can be written out in the JSON format using bin/makeJson.py and can be fed to brilCalc, which would then give us the exact integrated luminosity that went into a given job.
A sample job configuration for using the RunLumiListMod can be found at macros/listLumi.py.
BooleanMod can be used to facilitate the job sequence construction. Filtering modules (those that issue SkipEvent) can be combined in an "expression" that bonds them with AND and OR, or inverts the decision (NOT), and the value of this expression for the event is used to veto or pass the event. Essentially arbitrary sequence can be formulated by combining the BooleanMods.
> Adding utility modules RunLumiListMod and BooleanMod

- PhysicsUtils/src/Bins.cc
- PhysicsUtils/src/QGTagger.cc
A forgotten pair of parenthesis was giving a very different result for quark-gluon tagging.
> fixing a stupid bug (forgot parenthesis)

- TreeMod/interface/HLTMod.h
- TreeMod/src/HLTMod.cc
HLTMod is great in that it can collect the trigger object collection of the given trigger for you, but it collects those from all filters. This means that when you do trigger object matching, you may end up with matching your offline object to e.g. just an L1 seed. If we want to match to the trigger objects from a specific HLT filter, such as the last filter of a path, there is no way around other than to actually know the filter name and pick out the objects from the filter by hand. In such cases, the object collection exported by the HLTMod is wasted, and so it makes sense to be able to turn off this feature.
> HLTMod: Adding an option to not process TriggerObjects (i.e. work as a simple HLT filter)

- DataUtil/src/Cacher.cc
- PhysicsMod/dict/TemplateModsLinkDef.h
- PhysicsMod/interface/FastJetMod.h
- PhysicsMod/interface/FilterMod.h
- PhysicsMod/interface/TemplateMods.h
- PhysicsMod/src/FastJetMod.cc
- PhysicsMod/src/FilterMod.cc
- bin/setupExternal.sh
* Reworked FastJetMod so that we can recluster PFJets and GenJets.
* Added an option in the FilterMod (object selector) to filter also on particle ids, in addition to pT and eta. The PID filter only applies to PFCandidates and MCParticles.
* Accidental update on Cacher, which makes all files to be copied to the local disk when the "full-local" flag is on. The flag is off by default, so this basically won't affect anyone.
> adding new features to physics modules

- DataTree/dict/PFTauColLinkDef.h
- DataTree/interface/MCParticle.h
- DataTree/interface/PFCandidate.h
- DataTree/interface/PFTau.h
- DataTree/interface/RunInfo.h
- DataTree/src/PFCandidate.cc
- DataTree/src/PFTau.cc
- bin/requestFile.sh
- bin/runOnDatasets.py
PFTau: Updated the list of discriminators. Reduced the number of active discriminators.
MCParticle: PDG ID enum was wrong.
PFCandidate: Removed conversion reference. GED e/gamma objects are made from multiple PF candidates, so it does not make sense for the individual PF candidates to have a reference to a conversion object.
RunInfo: EvtSelData (MET filters) is now filled in a similar manner to HLT, i.e. the list of active filters in each file is stored in a separate tree. RunInfo holds the entry number in this tree.
> Dataformat for 043

- PhysicsMod/src/PlotKineMod.cc
This is the new way to tell ROOT that the TH1 can be rebinned automatically.
> SetBit(kCanRebin) -> SetCanExtend(kXaxis)

- DataTree/interface/Electron.h
- DataTree/interface/FatJet.h
- DataTree/interface/PFCandidate.h
- DataTree/interface/Photon.h
- DataTree/interface/SuperCluster.h
- DataTree/interface/XlFatJet.h
- PhysicsMod/src/PlotKineMod.cc
- bin/runOnDatasets.py
- bin/start.sh
* Egamma: moved supercluster variables to SuperCluster instead of having one each in Photon and Electron
* FatJet: moved variables that need to be filled at production time from XlFatJet
* PFCandidate: Cut out variables that weren't really used. Would like to slim down the Track object too but this needs more care to retain backward compatibility.
> Format slimming
